name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *' # Schedule the workflow to run daily, you can customize the schedule

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure upstream remote
        run: |
          git remote add upstream https://github.com/original-owner/original-repo.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main -m "Merge upstream changes"
          git push origin main
